job('DockerBuildandPublishDSL') {
    description('python list docker continers')
     scm {
        git {
        remote {
                url('https://github.com/gadido30/jenkins1/job1.git')
                //credentials('my-gihub-cred')
            }
            wrappers {
                preBuildCleanup()
            } 
            branch('*/' + 'main')
        }
    }

    steps {
        dockerBuildAndPublish {
            repositoryName('gadido30/job1')
            registryCredentials('e6a34d22-3562-4e22-a525-012c681fece1')
        }
    }
}